# Generated by Django 5.2.3 on 2025-08-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0022_remove_order_seen_order_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('image_field', models.FileField(upload_to='qr_codes/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='menus.restaurant')),
            ],
        ),
    ]
