# Generated by Django 5.2.3 on 2025-08-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrimage',
            name='image_field',
            field=models.FileField(default=None, null=True, upload_to='qr_codes/'),
        ),
    ]
