# Generated by Django 5.2.3 on 2025-08-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_remove_order_seen_order_new'),
        ('qrgenerator', '0002_alter_qrimage_image_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrimage',
            unique_together={('table_number', 'restaurant')},
        ),
    ]
