# Generated by Django 5.2.3 on 2025-08-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0003_alter_qrimage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrimage',
            name='image_field',
            field=models.FileField(default='', upload_to='qr_codes/'),
            preserve_default=False,
        ),
    ]
