# Generated by Django 5.2.1 on 2025-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='till_number',
            field=models.IntegerField(null=True),
        ),
    ]
