# Generated by Django 5.2.1 on 2025-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_restaurant_till_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list, null=True),
        ),
    ]
