# Generated by Django 5.2.1 on 2025-05-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_order_items_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(unique=True)),
                ('table_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('items', models.JSONField(default=list, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menus.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='menus.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
