# Generated by Django 5.2.1 on 2025-05-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_paidorder_pendingorder_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='items',
        ),
        migrations.CreateModel(
            name='PaidItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_items', to='menus.item')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_items', to='menus.paidorder')),
            ],
        ),
        migrations.CreateModel(
            name='PendingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='menus.item')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='menus.pendingorder')),
            ],
        ),
    ]
