# Generated by Django 5.2.1 on 2025-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_paidorder_items_remove_pendingorder_items_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaidItems',
            new_name='PaidItem',
        ),
        migrations.RenameModel(
            old_name='PendingItems',
            new_name='PendingItem',
        ),
        migrations.RenameField(
            model_name='paiditem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='paiditem',
            old_name='reference_number',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='pendingitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='pendingitem',
            old_name='reference_number',
            new_name='oder',
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='table_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
