# Generated by Django 5.2.1 on 2025-05-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_rename_paiditems_paiditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='table_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='table_number',
            field=models.IntegerField(null=True),
        ),
    ]
