# Generated by Django 5.2.1 on 2025-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_paidorder_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiditem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
