# Generated by Django 5.2.1 on 2025-06-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_paiditem_quantity_pendingitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pendingitem',
            name='oder',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='restaurant',
        ),
        migrations.RenameModel(
            old_name='PaidOrder',
            new_name='Order',
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='menus.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='menus.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='menus.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='PaidItem',
        ),
        migrations.DeleteModel(
            name='PendingItem',
        ),
        migrations.DeleteModel(
            name='PendingOrder',
        ),
    ]
