# Generated by Django 5.2.1 on 2025-06-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_remove_pendingitem_item_remove_pendingitem_oder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
