# Generated by Django 5.2.1 on 2025-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='id',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='ordered_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
