# Generated by Django 5.2.1 on 2025-06-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_ordereditem_id_ordereditem_ordered_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menus.item'),
        ),
    ]
