# Generated by Django 5.2.1 on 2025-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_alter_ordereditem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
