# Generated by Django 5.2.3 on 2025-08-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_remove_order_paid_alter_item_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
