# Generated by Django 5.2.3 on 2025-08-04 07:58

import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=menus.models.LowercaseTextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=menus.models.LowercaseTextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=menus.models.LowercaseTextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
