# Generated by Django 5.2.3 on 2025-08-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_rename_item_description_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
