# Generated by Django 5.2.3 on 2025-08-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_restaurant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='item_images/'),
        ),
    ]
