# Generated by Django 5.2.3 on 2025-08-17 20:09

import menus.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0019_item_unit_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=menus.models.PhoneNumber(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=menus.models.PhoneNumber(max_length=15, null=True),
        ),
    ]
