# Generated by Django 5.2.3 on 2025-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0020_alter_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
