# Generated by Django 5.2.3 on 2025-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0021_order_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seen',
        ),
        migrations.AddField(
            model_name='order',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
