# Generated by Django 5.2.3 on 2025-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_remove_order_seen_order_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
