# Generated by Django 5.2.3 on 2025-09-04 12:04

import django.db.models.deletion
import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0023_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', menus.models.LowercaseTextField(max_length=50)),
                ('national_id', models.IntegerField(unique=True)),
                ('phone_number', menus.models.PhoneNumber(max_length=15, unique=True)),
                ('pin_hash', models.CharField(blank=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menus.waiter'),
        ),
    ]
