# Generated by Django 5.2.3 on 2025-09-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0024_waiter_order_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='pin_hash',
            new_name='pin',
        ),
    ]
