# Generated by Django 5.2.3 on 2025-09-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0025_rename_pin_hash_waiter_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='menus.restaurant'),
        ),
    ]
