# Generated by Django 5.2.3 on 2025-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0026_alter_waiter_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('drinks', 'drinks'), ('food', 'food')], default=None, max_length=20, null=True),
        ),
    ]
